version: 2
updates:
  # SECURITY NOTE: Deno dependencies disabled intentionally
  # - Deno uses URL-based imports with version pinning and integrity hashes
  # - Manual review prevents supply chain attacks
  # - All dependencies locked in deno.lock with cryptographic verification

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "github-actions"
