version: 2
updates:
  # DISABLED: Deno uses URL-based imports, no package.json dependencies
  # - package-ecosystem: "bun"
  # Deno dependencies are managed via URL imports in deno.json
  # No automatic updates needed - manual review preferred for security

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "github-actions"
