name: "🚀 [FEATURE] Feature Request"
description: Request a new feature or enhancement for mikrus CLI
title: "[FEATURE] "
labels: []
projects: []
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ## 🚀 Feature Request
        Thank you for taking the time to suggest a new feature! Please fill out the information below to help us understand your request.
        
  - type: textarea
    id: feature-description
    attributes:
      label: "📝 Feature Description"
      description: "Provide a clear and detailed description of the feature you'd like to see implemented"
      placeholder: "Describe the feature you want..."
      value: ""
    validations:
      required: true
      
  - type: textarea
    id: problem-solving
    attributes:
      label: "🎯 Problem This Feature Would Solve"
      description: "Explain what problem this feature would solve or what improvement it would bring"
      placeholder: "This feature would solve..."
      value: ""
    validations:
      required: true
      
  - type: textarea
    id: proposed-solution
    attributes:
      label: "💡 Proposed Solution"
      description: "Describe how you envision this feature working"
      placeholder: "I think this could be implemented by..."
      value: ""
    validations:
      required: true
      
  - type: textarea
    id: alternatives-considered
    attributes:
      label: "🔄 Alternatives Considered"
      description: "Have you considered any alternative solutions or features?"
      placeholder: "Alternative approaches could be..."
      value: ""
    validations:
      required: false
      
  - type: dropdown
    id: feature-category
    attributes:
      label: "📂 Feature Category"
      description: "What category does this feature belong to?"
      options:
        - CLI Commands
        - Code Generation
        - Configuration
        - Documentation
        - Performance
        - Security
        - User Experience
        - API Integration
        - Other
    validations:
      required: true
      
  - type: dropdown
    id: priority
    attributes:
      label: "⚡ Priority Level"
      description: "How important is this feature to you?"
      options:
        - "Low - Nice to have"
        - "Medium - Would improve workflow"
        - "High - Essential for productivity"
        - "Critical - Blocking current work"
    validations:
      required: true
      
  - type: textarea
    id: use-case
    attributes:
      label: "🔍 Use Case Example"
      description: "Provide a specific example of how you would use this feature"
      placeholder: |
        Example scenario:
        1. I run mikrus command...
        2. The feature does...
        3. This helps me because...
      value: ""
    validations:
      required: false
      
  - type: textarea
    id: mockup-cli-output
    attributes:
      label: "💻 Expected CLI Output/Behavior (Optional)"
      description: "If applicable, show what the CLI output or behavior should look like"
      render: bash
      placeholder: |
        $ mikrus new-feature --option value
        ✅ Feature executed successfully
        📄 Generated files: ...
      value: ""
    validations:
      required: false
      
  - type: textarea
    id: additional-context
    attributes:
      label: "📚 Additional Context"
      description: "Add any other context, screenshots, or relevant information"
      placeholder: "Any additional information that might be helpful..."
      value: ""
    validations:
      required: false
      
  - type: checkboxes
    id: feature-checklist
    attributes:
      label: "✅ Feature Request Checklist"
      description: "Please confirm the following:"
      options:
        - label: "I have searched existing issues to ensure this feature hasn't been requested before"
          required: true
        - label: "This feature request is related to the mikrus CLI tool"
          required: true
        - label: "I have provided enough detail for the feature to be understood and implemented"
          required: true
        - label: "I am willing to help test this feature once implemented"
          required: false