name: Claude Code Review

on:
  # Trigger on pull requests to master
  pull_request:
    branches: [master]
    types: [opened, synchronize, reopened]
  # Manual trigger for full project review
  workflow_dispatch:

jobs:
  claude-review:
    # Optional: Filter by PR author
    # if: |
    #   github.event.pull_request.user.login == 'external-contributor' ||
    #   github.event.pull_request.user.login == 'new-developer' ||
    #   github.event.pull_request.author_association == 'FIRST_TIME_CONTRIBUTOR'

    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: read
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    steps:
      - name: Checkout repository
        id: deno_claude_checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 1

      - name: Run Claude Code Review
        id: deno_claude_review
        uses: anthropics/claude-code-action@a6888c03f22170d00d2a92fa2317584ca7d5e108 # v1.0
        with:
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          github_token: ${{ secrets.CLAUDE_CODE_REVIEW_PAT }}

          # Direct prompt for project review with validation checks
          prompt: |
            Please perform a comprehensive code review of the entire project. 
            
            FIRST, run these validation checks:
            1. Run all tests: `deno task test`
            2. Check types: `deno task check`
            3. Run linter: `deno task lint`
            4. Check formatting: `deno task fmt:check`
            5. Validate GitHub Actions workflows syntax in .github/workflows/
            
            THEN provide detailed feedback on:
            - Test results: Are all tests passing? Any failures or issues?
            - Type checking: Any TypeScript type errors or warnings?
            - Linting issues: Any code style or quality problems?
            - Workflow validation: Are all GitHub Actions workflows syntactically correct?
            - Overall code quality and architecture
            - Security vulnerabilities or concerns
            - Performance considerations
            - Code maintainability and documentation
            - Suggestions for improvements
            
            Report any failures or issues found during the validation checks first, then provide general code review feedback.

          # Optional: Use sticky comments to make Claude reuse the same comment on subsequent pushes to the same PR
          use_sticky_comment: true

          # Optional: Customize review based on file types
          # direct_prompt: |
          #   Review this PR focusing on:
          #   - For TypeScript files: Type safety and proper interface usage
          #   - For API endpoints: Security, input validation, and error handling
          #   - For React components: Performance, accessibility, and best practices
          #   - For tests: Coverage, edge cases, and test quality

          # Optional: Different prompts for different authors
          # direct_prompt: |
          #   ${{ github.event.pull_request.author_association == 'FIRST_TIME_CONTRIBUTOR' &&
          #   'Welcome! Please review this PR from a first-time contributor. Be encouraging and provide detailed explanations for any suggestions.' ||
          #   'Please provide a thorough code review focusing on our coding standards and best practices.' }}

          # Note: Claude Code Action will have access to standard tools for validation checks

          # Optional: Skip review for certain conditions
          # if: |
          #   !contains(github.event.pull_request.title, '[skip-review]') &&
          #   !contains(github.event.pull_request.title, '[WIP]')

# ORGANIZATION SECRETS:
# Uses organization-level secrets for Claude Code integration:
# - CLAUDE_CODE_OAUTH_TOKEN: OAuth token for Claude Code API access
# - ANTHROPIC_API_KEY: Anthropic API key for Claude model access
# Both secrets are configured at the organization level for security

