name: Code Quality

on:
  workflow_call:
    inputs:
      node-version:
        required: false
        type: string
        default: '20'
      bun-version:
        required: false
        type: string
        default: 'latest'
    outputs:
      quality-check:
        description: "Result of code quality checks"
        value: ${{ jobs.quality.outputs.result }}

jobs:
  quality:
    name: Code Quality Checks
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.quality-result.outputs.result }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: ${{ inputs.bun-version }}

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Run Biome format check
        run: bun run format --write=false

      - name: Run Biome lint check
        run: bun run lint

      - name: TypeScript compilation check
        run: bun run compile

      - name: Set quality result
        id: quality-result
        run: echo "result=success" >> $GITHUB_OUTPUT