name: Code Quality

on:
  workflow_call:
    inputs:
      node-version:
        required: false
        type: string
        default: '20'
      bun-version:
        required: false
        type: string
        default: 'latest'
    outputs:
      quality-check:
        description: "Result of code quality checks"
        value: ${{ jobs.quality.outputs.result }}

permissions:
  contents: read

jobs:
  quality:
    name: Code Quality Checks
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      result: ${{ steps.quality-result.outputs.result }}
    steps:
      - name: Checkout code
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4

      - name: Setup Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: ${{ inputs.node-version }}

      - name: Setup Bun
        uses: oven-sh/setup-bun@735343b667d3e6f658f44d0eca948eb6282f2b76 # v1
        with:
          bun-version: ${{ inputs.bun-version }}

      - name: Cache dependencies
        uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # v4
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lock') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Add node_modules/.bin to PATH
        run: echo "./node_modules/.bin" >> $GITHUB_PATH

      - name: Run Biome format check
        run: bun run format --write=false

      - name: Run Biome lint check
        run: bun run lint

      - name: TypeScript compilation check
        run: bun run compile

      - name: Set quality result
        id: quality-result
        run: echo "result=success" >> $GITHUB_OUTPUT