name: "🦕 Deno Dependabot Automation"

# Automated dependency management with intelligent merge policies
# Triggers: Dependabot PR opened/updated/reopened
# Purpose: Auto-merge safe updates (patch + dev minor), alert on major updates

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: write
  pull-requests: write

jobs:
  deno-dependabot-automation:
    name: "🦕 Deno Dependabot: Smart Dependency Management"
    # Automatically handles dependency updates with safety checks and merge policies
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' && github.repository_owner == 'gander-tools' }}
    steps:
      - name: "📊 Metadata: Extract Update Information"
        # Retrieves dependency update details (type, version change, dependency scope)
        id: deno_dependabot_metadata
        uses: dependabot/fetch-metadata@08eff52bf64351f401fb50d4972fa95b9f2c2d1b # v2.4.0
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"

      - name: "✅ Auto-merge: Patch Updates (Safe)"
        # Automatically merges patch version updates (bug fixes) as they are low-risk
        id: deno_dependabot_patch_merge
        if: steps.deno_dependabot_metadata.outputs.update-type == 'version-update:semver-patch'
        run: |
          gh pr merge --auto --squash --delete-branch "$PR_URL"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}

      - name: "🔄 Auto-merge: Dev Dependencies Minor Updates"
        # Auto-merges minor updates for development dependencies (tooling, testing)
        id: deno_dependabot_dev_minor_merge
        if: steps.deno_dependabot_metadata.outputs.update-type == 'version-update:semver-minor' && steps.deno_dependabot_metadata.outputs.dependency-type == 'direct:development'
        run: |
          gh pr merge --auto --squash --delete-branch "$PR_URL"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}

      - name: "🚨 Alert: Major Version Update Detected"
        # Flags major updates for manual review as they may contain breaking changes
        id: deno_dependabot_major_alert
        if: steps.deno_dependabot_metadata.outputs.update-type == 'version-update:semver-major'
        run: |
          gh pr comment "$PR_URL" --body "🚨 Major version update detected. Please review manually before merging."
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}
