name: "⚡ Node Automated Code Review (Claude)"

# Automated pull request reviews using Claude AI
# Triggers: ONLY PR opened/synchronized (automatic, no @claude needed)
# Purpose: Comprehensive automated code quality analysis and security review

on:
  pull_request:
    types: [opened, synchronize]
    # Optional: Only run on specific file changes
    # paths:
    #   - "src/**/*.ts"
    #   - "src/**/*.tsx"
    #   - "src/**/*.js"
    #   - "src/**/*.jsx"

jobs:
  node-automated-pr-review:
    name: "⚡ Node Claude AI: Automated Pull Request Review"
    # Comprehensive automated review for code quality, security, and best practices
    # Optional: Filter by PR author
    # if: |
    #   github.event.pull_request.user.login == 'external-contributor' ||
    #   github.event.pull_request.user.login == 'new-developer' ||
    #   github.event.pull_request.author_association == 'FIRST_TIME_CONTRIBUTOR'
    
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write # Minimal write access for comments only
      issues: read
      id-token: write
    
    steps:
      - name: "📥 Repository: Checkout PR Code"
        # Downloads PR changes for comprehensive code analysis
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
        with:
          fetch-depth: 1
          # Security: Prevent token exposure in URLs
          persist-credentials: false

      - name: "🧠 Claude AI: Analyze Code Changes"
        # Performs automated code review using Claude AI with TypeScript CLI focus
        id: claude-review
        uses: anthropics/claude-code-action@a47fdbe49f641eadaf74042deb4cd9dfb8a981d5 # Pinned SHA for security
        timeout-minutes: 15 # Security: Prevent long-running executions
        env:
          # Security: Limit environment variable exposure
          NODE_ENV: production
        with:
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}

          # Optional: Specify model (defaults to Claude Sonnet 4, uncomment for Claude Opus 4.1)
          # model: "claude-opus-4-1-20250805"

          # MAXIMUM EFFECTIVENESS: Production-Grade Automated Review
          direct_prompt: |
            🔍 COMPREHENSIVE PRODUCTION-GRADE CODE REVIEW
            You are a senior TypeScript/CLI security expert. Perform RIGOROUS analysis.
            
            🚨 CRITICAL SECURITY AUDIT (FAIL ON ANY VIOLATION):
            ❌ Command injection vulnerabilities (process.exec, child_process)
            ❌ Path traversal attacks (../../, resolve() without validation)
            ❌ Unsafe user input processing (eval, Function constructor)
            ❌ Hardcoded secrets/credentials/API keys
            ❌ Insecure file permissions (777, world-writable)
            ❌ SQL injection patterns (if database operations)
            ❌ Prototype pollution vulnerabilities
            
            🔒 CLI SECURITY CHECKLIST:
            ✅ Input sanitization on ALL user arguments
            ✅ File path validation (stay within project bounds)
            ✅ Error messages don't leak sensitive info
            ✅ Proper exit codes (0 success, 1+ errors)
            ✅ Resource cleanup (streams, processes, temp files)
            
            📋 CODE QUALITY ENFORCEMENT (ZERO TOLERANCE):
            ❌ TypeScript `any` usage (must use proper types)
            ❌ Missing error handling (try/catch, .catch())
            ❌ Unused imports/variables/functions
            ❌ Console.log in production code
            ❌ Hardcoded values (use constants/config)
            ❌ Biome rule violations
            ❌ Missing JSDoc for public APIs
            
            🧪 TESTING REQUIREMENTS (MANDATORY):
            ✅ Unit tests for ALL new functions
            ✅ Integration tests for CLI commands
            ✅ Edge case testing (empty inputs, invalid paths)
            ✅ Error scenario testing
            ✅ Mock external dependencies
            ✅ Test coverage >80% for new code
            
            ⚡ PERFORMANCE OPTIMIZATION:
            ❌ Synchronous file operations (use async)
            ❌ Memory leaks (unclosed streams/handlers)
            ❌ Inefficient loops (O(n²) when O(n) possible)
            ❌ Large bundle size increases
            ❌ Blocking operations on main thread
            
            🏗️ ARCHITECTURE COMPLIANCE:
            ✅ Follow Gluegun CLI conventions
            ✅ Proper command structure in src/commands/
            ✅ Consistent toolbox usage
            ✅ Template usage for code generation
            ✅ Extension patterns for new features
            
            📦 DEPENDENCY SECURITY:
            ❌ Known vulnerable package versions
            ❌ Unnecessary dependency additions
            ❌ Dev dependencies in production
            ❌ Packages without version pinning
            
            🎯 REVIEW OUTPUT FORMAT:
            Use this EXACT structure:
            
            ## 🚨 CRITICAL ISSUES (MUST FIX BEFORE MERGE)
            [List blocking security/quality issues]
            
            ## ⚠️ MAJOR ISSUES (FIX RECOMMENDED)  
            [List important improvements needed]
            
            ## 💡 MINOR IMPROVEMENTS (OPTIONAL)
            [List nice-to-have optimizations]
            
            ## ✅ POSITIVE OBSERVATIONS
            [Highlight good practices found]
            
            ## 📊 REVIEW SUMMARY
            - Security Score: X/10
            - Quality Score: X/10  
            - Test Coverage: X%
            - Performance Impact: [LOW/MEDIUM/HIGH]
            - Recommendation: [APPROVE/CHANGES_NEEDED/REJECT]
            
            Be RUTHLESS but CONSTRUCTIVE. Include code examples and specific line references.

          # Optional: Use sticky comments to make Claude reuse the same comment on subsequent pushes to the same PR
          # use_sticky_comment: true
          
          # Optional: Customize review based on file types
          # direct_prompt: |
          #   Review this PR focusing on:
          #   - For TypeScript files: Type safety and proper interface usage
          #   - For API endpoints: Security, input validation, and error handling
          #   - For React components: Performance, accessibility, and best practices
          #   - For tests: Coverage, edge cases, and test quality
          
          # Optional: Different prompts for different authors
          # direct_prompt: |
          #   ${{ github.event.pull_request.author_association == 'FIRST_TIME_CONTRIBUTOR' && 
          #   'Welcome! Please review this PR from a first-time contributor. Be encouraging and provide detailed explanations for any suggestions.' ||
          #   'Please provide a thorough code review focusing on our coding standards and best practices.' }}
          
          # Security: Restrict to read-only analysis and safe validation commands
          allowed_tools: "Bash(bun run test),Bash(bun run check),Bash(bun run lint)"
          
          # Optional: Skip review for certain conditions
          # if: |
          #   !contains(github.event.pull_request.title, '[skip-review]') &&
          #   !contains(github.event.pull_request.title, '[WIP]')

